apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: asdsa
  name: bp-test1
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.12.0
  componentsCriticality:
  - name: opa-policy
  - name: network-policy
  - name: cost-profile
  - name: trivy-addon
  - name: test-xwing
  - name: test-nginx1
  - name: test-alert
  costProfile:
    name: default-cost-profile-aws
    version: version-1733990011
  customAddons:
  - name: trivy-addon
    version: version1
  - dependsOn:
    - test-nginx1
    name: test-xwing
    version: version1
  - dependsOn:
    - trivy-addon
    name: test-nginx1
    version: cc1
  - name: test-alert
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator:
        enabled: true
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  networkPolicy:
    policies:
    - name: ccnp1
      version: v1
    profile:
      name: default
      version: latest
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1733990011
    profile:
      name: default
      version: latest
  type: custom
  version: version3
